name: Node.js CI

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - run: npm run build --if-present

      - run: npm test -- --passWithNoTests
